trigger:
  branches:
    include:
      - master  # or 'master', or whichever branch you want to trigger on
pool:
  name: Default
  vmImage: 'ubuntu-latest'

variables:
  imageName: ayoubaitbarka/boutiquefront

steps:
- task: DockerInstaller@0
  displayName: Install Docker

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    repository: $(imageName)
    Dockerfile: Dockerfile
    tags: latest

- task: Docker@2
  displayName: Push Image to Docker Hub
  inputs:
    command: push
    repository: $(imageName)
    tags: latest
    containerRegistry: dockerhubservice  # must match your Docker Hub connection name

